name: Main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Build
        run: |
          make compile KM=default
          make compile KM=jis
          make compile KM=via
          mkdir build
          mv ./firmware/qmk_firmware/tmp_dya_jis.uf2 build/dya_jis.uf2
          mv ./firmware/qmk_firmware/tmp_dya_default.uf2 build/dya_us.uf2
          mv ./firmware/qmk_firmware/tmp_dya_via.uf2 build/via.uf2

      - uses: actions/upload-artifact@v4
        with:
          name: dya_qmk_latest
          path: build
          overwrite: true
